# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c33f450b7ee55c2d4eaa7b22f31f34e97a884e6724dab0544491526a8e148ed25b25fd23160730dafa2e63ba4589b2020e57b9558df5636267c3f587bd1e3d17
  stripe_publishable_key: pk_test_63QWQ6wSTuAUfZPFqFugXhdi
  stripe_secret_key: sk_test_qHja3XEmavOVI9aagh7Kb7DE
test:
  secret_key_base: 79a5dd13dfcfd1c81f7a79e7601b9791632f46b2b927c5287e7bcbfd2ae730b239877e59a78b45f2473cb645f0991b3007fff6a38d9ac8db1374c7c30921a83c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: ENV['stripe_publishable_key']
  stripe_secret_key: ENV['stripe_publishable_key']
